/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void calcprog_1(char *host, double a, double b, char op, coordenadas ca, coordenadas cb, arr va, arr vb) {
	CLIENT *clnt;
	dresponse  *result;

	#ifndef	DEBUG
		clnt = clnt_create (host, CALCPROG, CALCVERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */


	switch (op) {
		case '+':
			result = suma_1(a, b, clnt);
			break;
		case '-':
			result = resta_1(a, b, clnt);
			break;
		case 'x':
			result = multiplica_1(a, b, clnt);
			break;
		case '/':
			result = divide_1(a, b, clnt);
			break;
		case 'm':
			result = dmanhattan_1(ca, cb, clnt);
			break;
		case 'e':
			result = deuclides_1(ca, cb, clnt);
			break;
		default:
			printf ("op erronea\n");
			break;
	}

	if (result == (dresponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	if (op == 'm' || op == 'e') {
		printf("distancia %c ((%lf, %lf), (%lf, %lf))= %lf\n", op, ca.x, ca.y, cb.x, cb.y, result->dresponse_u.res);
	} else {
		printf("%lf %c %lf = %lf\n", a, op, b, result->dresponse_u.res);
	}

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}

int main (int argc, char *argv[]) {
	char *server;

	char type; // [b, d, v]

	char op; // [+, -, x, /] o [m, e] o [+, r]
	double a;
	double b;
	coordenadas ca;
	coordenadas cb;
	arr va;
	arr vb;

	if (argc != 2) {
		printf ("usage: %s server_server\n", argv[0]);
		exit (1);
	}

	server = argv[1];

	input: printf ("Elija tipo de operación:\n\tb (Básica + - x /)\n\td (cálculo de Distancia manhattan o euclidea)\n\tv (operaciones con Vectores: suma o reducción con suma)\n\tx eXit\n");
	scanf("%c", &type);

	if (type == 'b') {
		printf("Introduzca operación (operandoA operador operandoB, separados por espacios)(operandos disponibles: + - x /): ");
		scanf("%lf %c %lf", &a, &op, &b);

		printf("Op: %lf %c %lf\n", a, op, b);
	} else if (type == 'd') {
		double ax, ay, bx, by;
		printf("Introduzca coordenadas de los puntos y elija tipo de distancia (m (manhattan), e (euclides)) \ncoordenadaAX coordenadaAY coordenadaBX coordenadaBY operacion, separados por espacios: \n");
		scanf("%lf %lf %lf %lf %c", &ax, &ay, &bx, &by, &op);
		ca = (coordenadas){ax, ay};
		cb = (coordenadas){bx, by};

		printf("Op: distancia %c a=(%lf, %lf), b=(%lf, %lf)\n", op, ca.x, ca.y, cb.x, cb.y);
	} else if (type == 'v') {
		int length;
		printf("Introduzca tamaño de vector y operación (+ suma dos vectores, r reducción con suma de un vector: ");
		scanf("%d %c", &length, &op);
		va.arr_len = length;
		vb.arr_len = length;

		double auxA[length];
		double aux;
		for (int i = 0; i < length; i++) {
			printf("Introduzca A[%d]: ", i);
			scanf("%lf", &aux);
			auxA[i] = aux;
		}

		va.arr_val = auxA;

		if (op == '+') {
			double auxB[length];
			for (int i = 0; i < length; i++) {
				printf("Introduzca B[%d]: ", i);
				scanf("%lf", &aux);
				auxB[i] = aux;
			}
			vb.arr_val = auxB;
			printf("Suma de A[%d] y B[%d]\n", length, length);
		} else {
			printf("Reducción con suma de A[%d]\n", length);
		}

		printf("Operación con vectores de tamaño %d: %c\n", length, op);
	}

	if (type != 'x') {
		calcprog_1 (server, a, b, op, ca, cb, va, vb);
		type = NULL;
		fflush(stdin);
		goto input;
	}

	exit (0);
}
