/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void calcprog_1(char *host, double a, double b, char op, coordenadas ca, coordenadas cb) {
	CLIENT *clnt;
	dresponse  *result;

	#ifndef	DEBUG
		clnt = clnt_create (host, CALCPROG, CALCVERS, "udp");
		if (clnt == NULL) {
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */


	switch (op) {
		case '+':
			result = suma_1(a, b, clnt);
			break;
		case '-':
			result = resta_1(a, b, clnt);
			break;
		case 'x':
			result = multiplica_1(a, b, clnt);
			break;
		case '/':
			result = divide_1(a, b, clnt);
			break;
		case 'm':
			result = divide_1(a, b, clnt);
			break;
		default:
			printf ("op erronea\n");
			break;
	}

	if (result == (dresponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%lf %c %lf = %lf\n", a, op, b, result->dresponse_u.res);

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
}

int main (int argc, char *argv[]) {
	char *server;

	char type; // [b, c]

	char op; // [+, -, x, /] o [m, e]
	double a;
	double b;
	coordenadas ca;
	coordenadas cb;

	if (argc != 2) {
		printf ("usage: %s server_server\n", argv[0]);
		exit (1);
	}

	server = argv[1];


	printf ("Elija operación:\n\tb (básica + - x /)\n\tc (compleja distancia manhattan, distacia euclidea)\n");
	scanf("%c", &type);

	if (type == 'b') {
		printf ("Introduzca operación (operandoA operador operandoB, separados por espacios)(operandos disponibles: + - x /): ");
		scanf("%lf %c %lf", &a, &op, &b);

		printf("Op: %lf %c %lf\n", a, op, b);
	} else if (type == 'c') {
		printf ("Introduzca operación, operandos disponibles m (manhattan), e (euclides0)\n (operando coordenadaAX coordenadaAY coordenadaBX coordenadaBY, separados por espacios): ");
		scanf("%c %lf %lf %lf %lf", &op, &ca.x, &ca.y, &cb.x, &cb.y);

		printf("Op: distancia %c a=(%lf, %lf), b=(%lf, %lf)\n", op, ca.x, ca.y, cb.x, cb.y);
	} else {
		printf ("Opciones disponibles (b, c)\n");
		exit (1);
	}

	calcprog_1 (server, a, b, op, ca, cb);

	exit (0);
}
