/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"

dresponse *
suma_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static dresponse  result;

	/*
	 * insert server code here
	 */

	return &result;
}

dresponse *
resta_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static dresponse  result;

	/*
	 * insert server code here
	 */

	return &result;
}

dresponse *
multiplica_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static dresponse  result;

	/*
	 * insert server code here
	 */

	return &result;
}

dresponse *
divide_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static dresponse  result;

	/*
	 * insert server code here
	 */

	return &result;
}

dresponse *
dmanhattan_1_svc(coordenadas arg1, coordenadas arg2,  struct svc_req *rqstp)
{
	static dresponse  result;

	/*
	 * insert server code here
	 */

	return &result;
}

dresponse *
deuclides_1_svc(coordenadas arg1, coordenadas arg2,  struct svc_req *rqstp)
{
	static dresponse  result;

	/*
	 * insert server code here
	 */

	return &result;
}

vresponse *
sumavectores_1_svc(arr arg1, arr arg2,  struct svc_req *rqstp)
{
	static vresponse  result;

	/*
	 * insert server code here
	 */

	return &result;
}

dresponse *
reduce_1_svc(arr arg1,  struct svc_req *rqstp)
{
	static dresponse  result;

	/*
	 * insert server code here
	 */

	return &result;
}
