/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"


void
calcprog_1(char *host)
{
	CLIENT *clnt;
	dresponse  *result_1;
	double suma_1_arg1;
	double suma_1_arg2;
	dresponse  *result_2;
	double resta_1_arg1;
	double resta_1_arg2;
	dresponse  *result_3;
	double multiplica_1_arg1;
	double multiplica_1_arg2;
	dresponse  *result_4;
	double divide_1_arg1;
	double divide_1_arg2;
	dresponse  *result_5;
	coordenadas dmanhattan_1_arg1;
	coordenadas dmanhattan_1_arg2;
	dresponse  *result_6;
	coordenadas deuclides_1_arg1;
	coordenadas deuclides_1_arg2;
	vresponse  *result_7;
	arr sumavectores_1_arg1;
	arr sumavectores_1_arg2;
	dresponse  *result_8;
	arr reduce_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCPROG, CALCVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = suma_1(suma_1_arg1, suma_1_arg2, clnt);
	if (result_1 == (dresponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = resta_1(resta_1_arg1, resta_1_arg2, clnt);
	if (result_2 == (dresponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = multiplica_1(multiplica_1_arg1, multiplica_1_arg2, clnt);
	if (result_3 == (dresponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = divide_1(divide_1_arg1, divide_1_arg2, clnt);
	if (result_4 == (dresponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = dmanhattan_1(dmanhattan_1_arg1, dmanhattan_1_arg2, clnt);
	if (result_5 == (dresponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_6 = deuclides_1(deuclides_1_arg1, deuclides_1_arg2, clnt);
	if (result_6 == (dresponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_7 = sumavectores_1(sumavectores_1_arg1, sumavectores_1_arg2, clnt);
	if (result_7 == (vresponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_8 = reduce_1(reduce_1_arg1, clnt);
	if (result_8 == (dresponse *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calcprog_1 (host);
exit (0);
}
