/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "sumador.h"

dresponse *
suma_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static dresponse  result;

	xdr_free (xdr_dresponse, &result);
	result.dresponse_u.res = arg1 + arg2;

	printf("server: SUMA(%lf, %lf)=%lf\n", arg1, arg2, result);

	return &result;
}
