/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SUMADOR_H_RPCGEN
#define _SUMADOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dresponse {
	int errno;
	union {
		double res;
	} dresponse_u;
};
typedef struct dresponse dresponse;

struct suma_1_argument {
	double arg1;
	double arg2;
};
typedef struct suma_1_argument suma_1_argument;

#define SUMADOR 0x20000002
#define SUMADORV 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMA 1
extern  dresponse * suma_1(double , double , CLIENT *);
extern  dresponse * suma_1_svc(double , double , struct svc_req *);
extern int sumador_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMA 1
extern  dresponse * suma_1();
extern  dresponse * suma_1_svc();
extern int sumador_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dresponse (XDR *, dresponse*);
extern  bool_t xdr_suma_1_argument (XDR *, suma_1_argument*);

#else /* K&R C */
extern bool_t xdr_dresponse ();
extern bool_t xdr_suma_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SUMADOR_H_RPCGEN */
